/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TemplatesRouteRouteImport } from './routes/templates/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TemplatesIdRouteImport } from './routes/templates/$id'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardTemplatesRouteRouteImport } from './routes/dashboard/templates.route'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates.index'
import { Route as DashboardTemplatesCreateRouteImport } from './routes/dashboard/templates.create'
import { Route as DashboardTemplatesEditIdRouteImport } from './routes/dashboard/templates.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRouteRoute = TemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const TemplatesIdRoute = TemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TemplatesRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesRouteRoute = DashboardTemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTemplatesRouteRoute,
} as any)
const DashboardTemplatesCreateRoute =
  DashboardTemplatesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardTemplatesRouteRoute,
  } as any)
const DashboardTemplatesEditIdRoute =
  DashboardTemplatesEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => DashboardTemplatesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/templates': typeof TemplatesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard/templates': typeof DashboardTemplatesRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/dashboard/templates/create': typeof DashboardTemplatesCreateRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/templates/edit/$id': typeof DashboardTemplatesEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/dashboard/templates/create': typeof DashboardTemplatesCreateRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/templates/edit/$id': typeof DashboardTemplatesEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/templates': typeof TemplatesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard/templates': typeof DashboardTemplatesRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/dashboard/templates/create': typeof DashboardTemplatesCreateRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/templates/edit/$id': typeof DashboardTemplatesEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/templates'
    | '/about'
    | '/login'
    | '/dashboard/templates'
    | '/dashboard/users'
    | '/templates/$id'
    | '/dashboard/'
    | '/templates/'
    | '/dashboard/templates/create'
    | '/dashboard/templates/'
    | '/dashboard/templates/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard/users'
    | '/templates/$id'
    | '/dashboard'
    | '/templates'
    | '/dashboard/templates/create'
    | '/dashboard/templates'
    | '/dashboard/templates/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/templates'
    | '/about'
    | '/login'
    | '/dashboard/templates'
    | '/dashboard/users'
    | '/templates/$id'
    | '/dashboard/'
    | '/templates/'
    | '/dashboard/templates/create'
    | '/dashboard/templates/'
    | '/dashboard/templates/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  TemplatesRouteRoute: typeof TemplatesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/templates/$id': {
      id: '/templates/$id'
      path: '/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof TemplatesIdRouteImport
      parentRoute: typeof TemplatesRouteRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardTemplatesRouteRoute
    }
    '/dashboard/templates/create': {
      id: '/dashboard/templates/create'
      path: '/create'
      fullPath: '/dashboard/templates/create'
      preLoaderRoute: typeof DashboardTemplatesCreateRouteImport
      parentRoute: typeof DashboardTemplatesRouteRoute
    }
    '/dashboard/templates/edit/$id': {
      id: '/dashboard/templates/edit/$id'
      path: '/edit/$id'
      fullPath: '/dashboard/templates/edit/$id'
      preLoaderRoute: typeof DashboardTemplatesEditIdRouteImport
      parentRoute: typeof DashboardTemplatesRouteRoute
    }
  }
}

interface DashboardTemplatesRouteRouteChildren {
  DashboardTemplatesCreateRoute: typeof DashboardTemplatesCreateRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardTemplatesEditIdRoute: typeof DashboardTemplatesEditIdRoute
}

const DashboardTemplatesRouteRouteChildren: DashboardTemplatesRouteRouteChildren =
  {
    DashboardTemplatesCreateRoute: DashboardTemplatesCreateRoute,
    DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
    DashboardTemplatesEditIdRoute: DashboardTemplatesEditIdRoute,
  }

const DashboardTemplatesRouteRouteWithChildren =
  DashboardTemplatesRouteRoute._addFileChildren(
    DashboardTemplatesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardTemplatesRouteRoute: typeof DashboardTemplatesRouteRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardTemplatesRouteRoute: DashboardTemplatesRouteRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface TemplatesRouteRouteChildren {
  TemplatesIdRoute: typeof TemplatesIdRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteRouteChildren: TemplatesRouteRouteChildren = {
  TemplatesIdRoute: TemplatesIdRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteRouteWithChildren = TemplatesRouteRoute._addFileChildren(
  TemplatesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  TemplatesRouteRoute: TemplatesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
